name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6  # Replace with your version

      # Step 3: Terraform Init
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      # Step 4: Terraform Plan
      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan
